version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "DEPS UPDATE: "
    labels:
      - dependencies
    groups:
      core:
        patterns:
          - "^@xterm/addon-fit"
          - "^@xterm/xterm"
          - "^axios"
          - "^dotenv"
          - "^express"
          - "^monaco-editor"
          - "^node-pty"
          - "^semver"
          - "^socket.io"
      dev-deps:
        patterns:
          - "^eslint"
          - "^prettier"
          - "^@eslint"
          - "^husky"
          - "^jiti"
          - "^webpack"
          - "^monaco-editor-webpack-plugin"
          - "^style-loader"
          - "^css-loader"
          - "^terser-webpack-plugin"
          - "^baseline-browser-mapping"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ACTIONS UPDATE: "
    labels:
      - actions